services:
  scylladb:
    image: scylladb/scylla
    container_name: scylladb
    restart: unless-stopped # restart if docker crashes or restarts, but not when stopped
    expose:
      - "9042" # expose cql to other containers (go backend)
    networks:
      - internal 
    volumes:
      - scylla_data:/var/lib/scylla # data
      - scylla_logs:/var/log/scylla # logs
    command:
      - --smp 4 # cpu cores
      - --memory 4G # scylla requires memory to be explicitly set
      - --api-address 0.0.0.0 # listen on all interfaces
      - --developer-mode=1 # disables prod safety checks
  backend:
    build: ./backend
    container_name: backend
    depends_on:
      - scylladb # start scylladb before the go backend
    networks:
      - internal
      - public
    environment:
      - SCYLLA_HOST=scylladb # docker dns hostname for scylladb container
      - PEPPER_SECRET=TEMP_CHANGEME_TEMP
      - JWT_SECRET=TEMP_CHANGEME_TEMP
    restart: unless-stopped
    expose:
      - "8080" # expose http to other containers (nginx)
      - "2112" # expose metrics to other containers (prometheus)
    ports:
      - "9000:9000/tcp" # tcp game traffic
      - "9001:9001/udp" # udp game traffic
  nginx:
    image: nginx:stable-alpine
    container_name: nginx
    ports:
      - "80:80" # http exposed to lan
    depends_on:
      - backend
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/static/:/usr/share/nginx/html/:ro
    networks:
      - internal
      - public
    restart: unless-stopped
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--storage.tsdb.path=/prometheus"
      - "--storage.tsdb.retention.time=15d"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - prometheus-data:/prometheus
    depends_on:
      - backend
    networks:
      - internal
    expose:
      - "9090"
    restart: unless-stopped
  grafana:
    image: grafana/grafana
    container_name: grafana
    volumes:
      - grafana-data:/var/lib/grafana
      - ./grafana/grafana.ini:/etc/grafana/grafana.ini:ro
      - ./grafana/provisioning:/etc/grafana/provisioning:ro
      - ./grafana/provisioning/dashboards:/var/lib/grafana/dashboards:ro
    networks:
      - internal
      - public
    ports:
      - "3000:3000"
    depends_on:
      - prometheus
    restart: unless-stopped

networks:
  internal: # container to container networking
    driver: bridge 
  public:
    driver: bridge

volumes:
  scylla_data:
  scylla_logs:
  prometheus-data:
  grafana-data: