{
 "title": "Dashboard",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "panels": [
  { "title": "UDP", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Packet Processing Time",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(rate(udp_packet_processing_duration_seconds_sum[30s])) / sum(rate(udp_packet_processing_duration_seconds_count[30s]))",
     "legendFormat": "Mean"
    },
    {
     "expr": "histogram_quantile(\r\n  0.95,\r\n  sum by (le) (rate(udp_packet_processing_duration_seconds_bucket[30s]))\r\n)",
     "legendFormat": "95% High"
    }
   ]
  },
  {
   "title": "Bandwidth",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 6, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum(rate(udp_packet_received_size_bytes_sum[30s]))",
     "legendFormat": "RX"
    },
    {
     "expr": "sum(rate(udp_packet_sent_size_bytes_sum[30s]))",
     "legendFormat": "TX"
    }
   ]
  },
  {
   "title": "RX Packet Rate",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "rate(udp_packets_received_total[30s])",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Packet Errors",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "rate(udp_packet_errors_total[30s])",
     "legendFormat": "{{error}}"
    }
   ]
  },
  {
   "title": "TX Packet Rate",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "rate(udp_packets_sent_total[30s])",
     "legendFormat": "{{type}}"
    }
   ]
  },
  { "title": "Game", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 } },
  {
   "title": "Rooms",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 22 },
   "targets": [
    { "expr": "game_rooms", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Entities",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 22 },
   "targets": [
    { "expr": "game_entities", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Cached Chunks",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 22 },
   "targets": [
    { "expr": "game_cached_chunks", "legendFormat": "__auto" }
   ]
  },
  { "title": "TCP", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 } },
  {
   "title": "Active TCP Connections",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 6, "x": 0, "y": 33 },
   "targets": [
    { "expr": "tcp_active_connections", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Network Errors",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 7, "x": 6, "y": 33 },
   "targets": [
    {
     "expr": "rate(tcp_packet_errors_total[30s] + tcp_packet_send_errors_total[30s])",
     "legendFormat": "{{error}}"
    }
   ]
  },
  {
   "title": "RX Packet Rate",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 11, "x": 13, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "rate(tcp_packets_received_total[30s])",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Bandwidth",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum(rate(tcp_packet_received_size_bytes_sum[30s]))",
     "legendFormat": "RX"
    },
    {
     "expr": "sum(rate(tcp_packet_sent_size_bytes_sum[30s]))",
     "legendFormat": "TX"
    }
   ]
  },
  {
   "title": "TX Packet Rate",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "rate(tcp_packets_sent_total[30s])",
     "legendFormat": "{{type}}"
    }
   ]
  },
  { "title": "HTTP", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 53 } },
  {
   "title": "HTTP Request Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    { "expr": "rate(http_requests_total[30s])", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Request Duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, rate(http_request_duration_seconds_bucket[30s]))",
     "legendFormat": "95%"
    },
    {
     "expr": "rate(http_request_duration_seconds_sum[30s]) / rate(http_request_duration_seconds_count[30s])",
     "legendFormat": "Mean"
    }
   ]
  },
  { "title": "Auth", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 62 } },
  {
   "title": "Accounts",
   "type": "stat",
   "gridPos": { "h": 9, "w": 7, "x": 0, "y": 63 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "auth_accounts", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Sessions",
   "type": "stat",
   "gridPos": { "h": 9, "w": 8, "x": 7, "y": 63 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "auth_sessions", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Access Token Refreshes",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 9, "x": 15, "y": 63 },
   "targets": [
    { "expr": "auth_token_refreshes", "legendFormat": "__auto" }
   ]
  },
  { "title": "QR", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 72 } },
  {
   "title": "QR Codes",
   "type": "stat",
   "gridPos": { "h": 7, "w": 5, "x": 0, "y": 73 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "qr_qrcodes", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "QR Actions",
   "type": "stat",
   "gridPos": { "h": 7, "w": 5, "x": 5, "y": 73 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "qr_qractions", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "QR Scans",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 14, "x": 10, "y": 73 },
   "targets": [
    { "expr": "qr_qrscans", "legendFormat": "__auto" }
   ]
  }
 ]
}